/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_halfninja_videokit_Videokit */

#ifndef _Included_uk_co_halfninja_videokit_Videokit
#define _Included_uk_co_halfninja_videokit_Videokit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_initialise
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    setSize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_setSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    setBitRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_setBitRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    setFrameRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_setFrameRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    setInput
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_setInput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    setOutput
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_setOutput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    deinitialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_deinitialise
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    doStuff
 * Signature: (Landroid/graphics/Bitmap)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_doStuff(JNIEnv* env, jobject self, jobject bitmap);

/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_stop(JNIEnv* env, jobject self);

#ifdef __cplusplus
}
#endif
#endif

